---
inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/MethodParameterName:
  AllowedNames: [x, y, z]

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.6
